// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyManagement.Data;

namespace PropertyManagement.Migrations
{
    [DbContext(typeof(PropertyManagementDatabase))]
    [Migration("20201211022110_Prorerty")]
    partial class Prorerty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("PropertyManagement.Models.Customer_Detail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Customer_Detail");
                });

            modelBuilder.Entity("PropertyManagement.Models.Dealer_Detail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Dealer_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dealer_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Dealer_Detail");
                });

            modelBuilder.Entity("PropertyManagement.Models.Property_Detail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Property_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Property_Detail");
                });

            modelBuilder.Entity("PropertyManagement.Models.Property_Oction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Bid_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Customer_ID")
                        .HasColumnType("int");

                    b.Property<int>("Dealer_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Obj_Customer_DetailID")
                        .HasColumnType("int");

                    b.Property<int?>("Obj_Dealer_DetailsID")
                        .HasColumnType("int");

                    b.Property<int?>("Obj_property_DetailsID")
                        .HasColumnType("int");

                    b.Property<int>("Property_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Obj_Customer_DetailID");

                    b.HasIndex("Obj_Dealer_DetailsID");

                    b.HasIndex("Obj_property_DetailsID");

                    b.ToTable("Property_Oction");
                });

            modelBuilder.Entity("PropertyManagement.Models.Property_Oction", b =>
                {
                    b.HasOne("PropertyManagement.Models.Customer_Detail", "Obj_Customer_Detail")
                        .WithMany()
                        .HasForeignKey("Obj_Customer_DetailID");

                    b.HasOne("PropertyManagement.Models.Dealer_Detail", "Obj_Dealer_Details")
                        .WithMany()
                        .HasForeignKey("Obj_Dealer_DetailsID");

                    b.HasOne("PropertyManagement.Models.Property_Detail", "Obj_property_Details")
                        .WithMany()
                        .HasForeignKey("Obj_property_DetailsID");

                    b.Navigation("Obj_Customer_Detail");

                    b.Navigation("Obj_Dealer_Details");

                    b.Navigation("Obj_property_Details");
                });
#pragma warning restore 612, 618
        }
    }
}
