// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyManagement.Data;

namespace PropertyManagement.Migrations
{
    [DbContext(typeof(PropertyManagement_Database))]
    partial class PropertyManagement_DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("PropertyManagement.Models.Customer_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer_Detail");
                });

            modelBuilder.Entity("PropertyManagement.Models.Dealer_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Dealer_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dealer_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dealer_Detail");
                });

            modelBuilder.Entity("PropertyManagement.Models.Property_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Property_Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Property_Detail");
                });

            modelBuilder.Entity("PropertyManagement.Models.Property_Oction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<decimal>("Bid_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Customer_DetailId")
                        .HasColumnType("int");

                    b.Property<int>("Dealer_DetailId")
                        .HasColumnType("int");

                    b.Property<int>("Property_DetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Customer_DetailId");

                    b.HasIndex("Dealer_DetailId");

                    b.HasIndex("Property_DetailId");

                    b.ToTable("Property_Oction");
                });

            modelBuilder.Entity("PropertyManagement.Models.Property_Oction", b =>
                {
                    b.HasOne("PropertyManagement.Models.Customer_Detail", "Customer_Detail")
                        .WithMany()
                        .HasForeignKey("Customer_DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyManagement.Models.Dealer_Detail", "Dealer_Detail")
                        .WithMany()
                        .HasForeignKey("Dealer_DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyManagement.Models.Property_Detail", "Property_Detail")
                        .WithMany()
                        .HasForeignKey("Property_DetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer_Detail");

                    b.Navigation("Dealer_Detail");

                    b.Navigation("Property_Detail");
                });
#pragma warning restore 612, 618
        }
    }
}
